#!/usr/bin/env bash
# A script that transfer  a file from our client to a server

path=$1
ip_address=$2
user=$3
key=$4

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i $key $path $user@$ip_address:~/
fi
